import assert from 'node:assert/strict';
import test from 'node:test';
import { DistributedPhysicalMedium3DV1 } from '../src/core/physics/distributed-physical-medium.js';
import { sha } from '../src/util.js';
import { runDistributedMediumProbeBatchSyncV1 }
  from '../src/core/physics/distributed-medium-probe-parallel.js';
import { DistributedR1ExperienceStoreV1 } from '../src/core/learning/distributed-r1.js';
import type { Observation, RealEvent } from '../src/contracts.js';

function fixture() {
  const s0 = [1, 2, 3, 4], cue = [100, 101, 102, 103];
  const s1 = [1000, 1001, 1002, 1003], s2 = [2000, 2001, 2002, 2003];
  const medium = new DistributedPhysicalMedium3DV1({ name: 'anonymous-action-boundary' });
  for (let repetition = 0; repetition < 16; repetition++) {
    for (const [index, sequence] of [[s0, cue, s1], [s1, cue, s2]].entries()) {
      medium.applyEpisode({ version: 'DistributedEpisodeV1',
        traceId: `synthetic-${repetition}-${index}`, provenance: 'trusted-real-event',
        pulses: sequence.map((sites, ordinal) => ({ version: 'SparseFieldPulseV1',
          offset: ordinal * .04, drives: sites.map(siteId => ({ siteId, intensity: 1 })) })) });
    }
  }
  const stored = medium.snapshot();
  const snapshot = { ...stored, sites: stored.sites.map(site => ({ ...site, activation: 0 })) };
  return { s0, cue, s1, s2, snapshot };
}

test('one prescribed command cannot be regenerated by a later observed state', () => {
  const { s0, cue, s1, snapshot } = fixture();
  const query = DistributedPhysicalMedium3DV1.fromSnapshot(snapshot, cue);
  const before = sha(snapshot);
  for (let seed = 1n; seed <= 8n; seed++) {
    const first = query.probeConditionedSequence(s0, [cue], seed, 180);
    assert.equal(first.ambiguous, false);
    assert.deepEqual(first.coreSiteIds, s1, 'single input escaped across another action boundary');
  }
  assert.equal(sha(snapshot), before);
  assert.equal(sha(query.snapshot()), before, 'query boundary must not erase learned bonds');
});

test('a prescribed command still drives its learned outgoing consequence', () => {
  // This boundary test does not assert conditional discrimination by an
  // anonymous R1 lattice without learned R2A differential factors.
  const cue = [100, 101, 102, 103], result = [2000, 2001, 2002, 2003];
  const source = new DistributedPhysicalMedium3DV1({ name: 'explicit-command' });
  for (let i = 0; i < 16; i++) source.applyEpisode({ version: 'DistributedEpisodeV1',
    traceId: `synthetic-${i}`, provenance: 'trusted-real-event',
    pulses: [cue, result].map((sites, ordinal) => ({ version: 'SparseFieldPulseV1', offset: ordinal * .04,
      drives: sites.map(siteId => ({ siteId, intensity: 1 })) })) });
  const query = DistributedPhysicalMedium3DV1.fromSnapshot(source.snapshot(), cue);
  for (let seed = 1n; seed <= 8n; seed++) {
    const reached = query.probeSequential([cue], seed, 180);
    assert.deepEqual(reached.coreSiteIds, result);
    assert((reached.run.directedTransportMass ?? 0) > 0);
  }
});

test('serial and worker probes carry the same transient command boundary', () => {
  const { s0, cue, snapshot } = fixture();
  const jobs = [1n, 2n].map((seed, index) => ({ index, seed, steps: 180,
    kind: 'conditioned-sequential' as const, conditionSiteIds: s0, seedPulses: [cue] }));
  assert.deepEqual(runDistributedMediumProbeBatchSyncV1(snapshot, jobs, 2,
    { prescribedActionSiteIds: cue }), runDistributedMediumProbeBatchSyncV1(snapshot, jobs, 1,
    { prescribedActionSiteIds: cue }));
});

test('the action boundary is a transient query input, not erased experience', () => {
  const { s0, cue, s2, snapshot } = fixture();
  const source = DistributedPhysicalMedium3DV1.fromSnapshot(snapshot);
  const readout = source.probeConditionedSequence(s0, [cue], 1n, 180);
  assert.deepEqual(readout.coreSiteIds, s2, 'unconstrained associative propagation is still stored');
  assert(snapshot.learnedBonds.some(bond => bond.kind === 'plastic-directed'
    && cue.includes(bond.toSiteId)));
});

test('passive observation markers do not become externally prescribed motor ports', () => {
  const medium = new DistributedPhysicalMedium3DV1({ name: 'passive-boundary' });
  const store = new DistributedR1ExperienceStoreV1(medium);
  const frame = (sequence: number, selectedSlot: number): Observation => ({ sequence,
    activeSeconds: sequence * .05, contextId: 'anonymous', targetId: null, objects: [],
    self: { position: [0, 0, 0], yaw: 0, pitch: 0, properties: { selectedSlot } } });
  const passive: RealEvent = { version: 'RealEventV5', id: 'passive',
    cue: { kind: 'passive', parameters: {}, targetRole: null }, frames: [frame(1, 0), frame(2, 1)],
    trackedIds: ['self'], bodyResult: null, provenance: 'observed-passive', complete: true };
  store.observe(passive);
  assert.deepEqual(store.prescribedActionSiteIds(), []);
  const active: RealEvent = { ...passive, id: 'active',
    cue: { kind: 'select-hotbar', parameters: { slot: 2 }, targetRole: null },
    frames: [frame(3, 1), frame(4, 2)], provenance: 'executed-real-body',
    bodyResult: { action: { kind: 'select-hotbar', parameters: { slot: 2 } },
      executed: true, status: 'completed', startSequence: 3, endSequence: 4 } };
  const receipt = store.observe(active);
  assert.deepEqual(store.prescribedActionSiteIds(), receipt.record.episodeTopology.pulses[1]!
    .map(drive => drive.siteId).sort((a, b) => a - b));
});
